import torch
import numpy as np
import os
from models.nn_v0 import NN_v0

class WeightsExporter:
    """
    Exports PyTorch model weights to C++ header file (weights.h)
    for embedded inference on Teensy 4.1.
    """
    
    def __init__(self, model_path: str):
        self.model = NN_v0()
        # Load checkpoint (map_location ensures it works on CPU)
        checkpoint = torch.load(model_path, map_location='cpu')
        
        # Handle both full checkpoint dict and just state_dict
        if 'model_state_dict' in checkpoint:
            self.model.load_state_dict(checkpoint['model_state_dict'])
        else:
            self.model.load_state_dict(checkpoint)
            
        self.model.eval()
        
    def export_to_header(self, output_path: str = "firmware/weights.h"):
        """
        Iterates through all named parameters and writes them as C arrays.
        """
        print(f"Exporting weights to {output_path}...")
        
        with open(output_path, 'w') as f:
            f.write("// Auto-generated by weights_exporter.py\n")
            f.write("#ifndef WEIGHTS_H\n")
            f.write("#define WEIGHTS_H\n\n")
            f.write("#include <Arduino.h>\n\n")
            
            total_params = 0
            
            for name, param in self.model.named_parameters():
                # Sanitize name: "trunk.0.weight" -> "trunk_0_weight"
                c_name = name.replace('.', '_')
                
                # Flatten data
                data = param.detach().numpy().flatten()
                size = len(data)
                total_params += size
                
                # Write array definition
                f.write(f"// Shape: {list(param.shape)}\n")
                f.write(f"const float {c_name}[{size}] = {{\n")
                
                # Write data in chunks of 10 for readability
                for i in range(0, size, 10):
                    chunk = data[i:i+10]
                    line = ", ".join([f"{x:.6f}f" for x in chunk])
                    if i + 10 < size:
                        line += ","
                    f.write(f"    {line}\n")
                    
                f.write("};\n\n")
                
            f.write(f"// Total Parameters: {total_params}\n")
            f.write("#endif // WEIGHTS_H\n")
            
        print(f"Done! Total parameters: {total_params}")

if __name__ == "__main__":
    # Example usage - assumes a checkpoint exists
    # If no checkpoint exists, we export the initialized random weights (valid for testing pipeline)
    try:
        exporter = WeightsExporter("models/checkpoints/latest.pt")
    except FileNotFoundError:
        print("Warning: No checkpoint found. Exporting initialized weights for testing.")
        # Save a dummy checkpoint to load
        dummy = NN_v0()
        # Save this specific initialization for verification
        torch.save(dummy.state_dict(), "tests/test_model.pt")
        print("Saved temporary test model to tests/test_model.pt")
        
        # Reload it to ensure consistency
        exporter = WeightsExporter("tests/test_model.pt")
        
    exporter.export_to_header()
